### PR TITLE
Integration with codecov

### PR DESCRIPTION
**Pull request by seanoshea**
See https://github.com/material-foundation/material-text-accessibility-ios/pull/6 for the rationale behind this PR.

Would need someone under the umbrella of the `material-foundation` to actually enable integration with `codecov`. Otherwise the badge on the README will not reflect the latest coverage measure on master.

https://codecov.io/gh/seanoshea/material-text-accessibility-ios/commit/839e6231eb2e2cd32ddfb0e43a062921623ce0e8 shows what the current coverage is for the library which was generated by https://travis-ci.org/seanoshea/material-text-accessibility-ios/builds/148757829.

### CODE REVIEW

**Comment by ajsecord** [comment]
Thanks for the pull request! We have to check to see if we can grant codecov the permissions it wants.

**Comment by seanoshea** [comment]
@ajsecord - Sounds good. I'm a big fan of using code coverage. codecov acts as a nice gatekeeper for PRs & has pretty sweet github integrations. I should really try using it for some of my other projects.

**Comment by jverkoey** [comment]
The permissions for codecov are similar to Travis CI (no direct code access needed), so we should be good. I'll look into turning it on for the material-motion repos as well.

**Comment by ajsecord** [comment]
We just enabled material-foundation for codecov.io.

**Pull request merged**
